# .bashrc

# User specific aliases and functions

alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
alias rm='rm -i --preserve-root'
alias ds='du --max-depth=1|sort -n'


#Path
MAVEN_HOME=/usr/local/maven
export MAVEN_HOME
export PATH=$PATH:$MAVEN_HOME/bin
export PATH=$PATH:/usr/local/mysql/bin
export SPARK_HOME=/opt/spark
export PATH=$HOME/.pyenv/bin:$PATH
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


alias drun='function _drun() { docker run --rm -it --net=host -v $*:/search/proj/ docker.registry.clouddev.sogou:5000/library/spark-bigdl:1.0
 /bin/bash; unset -f _drun; }; _drun'

export EDITOR=vim
source ~/z.sh


LANG=zh_CN.utf8
LC_CTYPE="zh_CN.utf8"
LC_NUMERIC="zh_CN.utf8"
LC_TIME="zh_CN.utf8"
LC_COLLATE="zh_CN.utf8"
LC_MONETARY="zh_CN.utf8"
LC_MESSAGES="zh_CN.utf8"
LC_PAPER="zh_CN.utf8"
LC_NAME="zh_CN.utf8"
LC_ADDRESS="zh_CN.utf8"
LC_TELEPHONE="zh_CN.utf8"
LC_MEASUREMENT="zh_CN.utf8"
LC_IDENTIFICATION="zh_CN.utf8"
LC_ALL=zh_CN.utf8

